name: ENV Variables

on: issues
env:
  WF_ENV: ${{ secrets.WF_ENV }}

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Push a random file
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role: arn:aws:iam::859615181157:role/IAM_TEST_ROLE
